import type {
  SpamAdEmail,
  DraftEmail,
  EscalationAlert,
  UnsubscribeStatus,
} from "@/types/email";

export const mockSpamEmails: readonly SpamAdEmail[] = [
  {
    workflow: "email_inbox",
    category: "SPAM",
    email_id: "spam-001",
    sender_name: "Prize Center",
    sender_email: "winner@prize-center-eu.xyz",
    sender_domain: "prize-center-eu.xyz",
    subject: "Sie haben gewonnen! Klicken Sie hier",
    preview: "Herzlichen Glückwunsch! Sie wurden als Gewinner ausgewählt...",
    date: "2026-03-01T09:15:00Z",
    confidence: 0.98,
    low_confidence: false,
    reasoning: "Typische Gewinnspiel-Spam-Merkmale, verdächtige Domain",
    list_unsubscribe_url: null,
    list_unsubscribe_mailto: null,
    unsubscribe_available: false,
  },
  {
    workflow: "email_inbox",
    category: "SPAM",
    email_id: "spam-002",
    sender_name: "Konto Sicherheit",
    sender_email: "sicherheit@bank-verify.co",
    sender_domain: "bank-verify.co",
    subject: "Dringende Kontoüberprüfung erforderlich",
    preview: "Ihr Konto wurde vorübergehend gesperrt. Bestätigen Sie...",
    date: "2026-03-01T11:30:00Z",
    confidence: 0.96,
    low_confidence: false,
    reasoning: "Phishing-Versuch, gefälschte Bank-Domain",
    list_unsubscribe_url: null,
    list_unsubscribe_mailto: null,
    unsubscribe_available: false,
  },
  {
    workflow: "email_inbox",
    category: "SPAM",
    email_id: "spam-003",
    sender_name: "Buchhaltung Extern",
    sender_email: "rechnung@rechnungs-service24.biz",
    sender_domain: "rechnungs-service24.biz",
    subject: "Rechnung Nr. 2026-4821 — Zahlung überfällig",
    preview:
      "Im Anhang finden Sie die Rechnung Nr. 2026-4821 über 3.249,00 EUR. Bitte überweisen Sie...",
    date: "2026-02-28T14:20:00Z",
    confidence: 0.93,
    low_confidence: false,
    reasoning:
      "Gefälschte Rechnung, unbekannter Absender, verdächtige Domain mit Ziffern",
    list_unsubscribe_url: null,
    list_unsubscribe_mailto: null,
    unsubscribe_available: false,
  },
  {
    workflow: "email_inbox",
    category: "SPAM",
    email_id: "spam-004",
    sender_name: "Office 365 Team",
    sender_email: "support@ms-office-alerts.net",
    sender_domain: "ms-office-alerts.net",
    subject: "Your mailbox storage is almost full",
    preview:
      "Dear user, your Office 365 mailbox has reached 95% capacity. Click here to upgrade...",
    date: "2026-03-01T07:45:00Z",
    confidence: 0.58,
    low_confidence: true,
    reasoning:
      "Verdacht auf Phishing, aber Domain könnte legitim sein. Inhalt ähnelt echten Microsoft-Benachrichtigungen.",
    list_unsubscribe_url: null,
    list_unsubscribe_mailto: null,
    unsubscribe_available: false,
  },
];

export const mockAdEmails: readonly SpamAdEmail[] = [
  {
    workflow: "email_inbox",
    category: "AD",
    email_id: "ad-001",
    sender_name: "HubSpot",
    sender_email: "marketing@hubspot.com",
    sender_domain: "hubspot.com",
    subject: "Neue CRM-Funktionen für Ihr Team",
    preview: "Entdecken Sie unsere neuesten CRM-Updates und steigern Sie...",
    date: "2026-03-01T08:00:00Z",
    confidence: 0.92,
    low_confidence: false,
    reasoning: "Marketing-Newsletter von bekanntem SaaS-Anbieter",
    list_unsubscribe_url: "https://hubspot.com/unsubscribe/abc123",
    list_unsubscribe_mailto: null,
    unsubscribe_available: true,
  },
  {
    workflow: "email_inbox",
    category: "AD",
    email_id: "ad-002",
    sender_name: "AWS",
    sender_email: "aws-marketing@amazon.com",
    sender_domain: "amazon.com",
    subject: "AWS Summit Frankfurt 2026 — Jetzt anmelden",
    preview: "Sichern Sie sich Ihren Platz beim AWS Summit in Frankfurt...",
    date: "2026-02-28T10:15:00Z",
    confidence: 0.89,
    low_confidence: false,
    reasoning: "Event-Einladung, Werbecharakter",
    list_unsubscribe_url: "https://pages.awscloud.com/unsubscribe",
    list_unsubscribe_mailto: "unsubscribe@aws.amazon.com",
    unsubscribe_available: true,
  },
  {
    workflow: "email_inbox",
    category: "AD",
    email_id: "ad-003",
    sender_name: "Personio",
    sender_email: "noreply@personio.de",
    sender_domain: "personio.de",
    subject: "Produktupdate: Neue Recruiting-Features",
    preview:
      "Wir freuen uns, Ihnen unsere neuesten Recruiting-Features vorzustellen. Ab sofort können Sie...",
    date: "2026-03-01T06:30:00Z",
    confidence: 0.85,
    low_confidence: false,
    reasoning:
      "Produkt-Newsletter von bekanntem HR-Software-Anbieter, kein Abmeldelink im Header",
    list_unsubscribe_url: null,
    list_unsubscribe_mailto: null,
    unsubscribe_available: false,
  },
  {
    workflow: "email_inbox",
    category: "AD",
    email_id: "ad-004",
    sender_name: "Deutsche Bahn",
    sender_email: "angebote@bahn.de",
    sender_domain: "bahn.de",
    subject: "Frühbucherangebote: Sparpreise ab 17,90 EUR",
    preview:
      "Reisen Sie günstig mit der Bahn! Entdecken Sie unsere Frühbucherangebote für März und April...",
    date: "2026-02-27T09:00:00Z",
    confidence: 0.62,
    low_confidence: true,
    reasoning:
      "Sieht nach Werbemail aus, könnte aber auch als Servicemitteilung gewertet werden. Absender ist verifiziert.",
    list_unsubscribe_url: "https://bahn.de/newsletter/abmelden",
    list_unsubscribe_mailto: null,
    unsubscribe_available: true,
  },
];

export const mockUrgentDrafts: readonly DraftEmail[] = [
  {
    workflow: "email_inbox",
    category: "URGENT",
    email_id: "urgent-001",
    sender_name: "Thomas Müller",
    sender_email: "thomas.mueller@enterprise-gmbh.de",
    subject: "Re: Vertragsverlängerung — Frist läuft ab",
    original_subject: "Vertragsverlängerung — Frist läuft ab",
    original_preview:
      "Sehr geehrte Damen und Herren, die Frist für unsere Vertragsverlängerung läuft am 05.03. ab...",
    draft_html:
      "<p>Sehr geehrter Herr Müller,</p><p>vielen Dank für Ihre Nachricht bezüglich der Vertragsverlängerung.</p><p>Wir bestätigen, dass wir die Verlängerung bis zum [BITTE ERGÄNZEN: Datum] vornehmen werden.</p><p>Mit freundlichen Grüßen</p><p>[SIGNATUR EINFÜGEN]</p>",
    draft_plain:
      "Sehr geehrter Herr Müller,\n\nvielen Dank für Ihre Nachricht bezüglich der Vertragsverlängerung.\n\nWir bestätigen, dass wir die Verlängerung bis zum [BITTE ERGÄNZEN: Datum] vornehmen werden.\n\nMit freundlichen Grüßen\n[SIGNATUR EINFÜGEN]",
    placeholders: ["BITTE ERGÄNZEN: Datum"],
    reply_language: "de",
    confidence: 0.82,
    review_reason: "Fehlende Terminangabe",
    requires_human_review: true,
    low_confidence: false,
    is_escalated: false,
    sentiment_score: -0.1,
    date: "2026-03-01T14:30:00Z",
    timestamp: "2026-03-01T14:30:00Z",
  },
  {
    workflow: "email_inbox",
    category: "URGENT",
    email_id: "urgent-002",
    sender_name: "Sarah Klein",
    sender_email: "sarah.klein@partner-ag.de",
    subject: "Re: Dringende Lieferverzögerung",
    original_subject: "Dringende Lieferverzögerung",
    original_preview:
      "Hallo, leider müssen wir Ihnen mitteilen, dass sich die Lieferung um 2 Wochen verzögert...",
    draft_html:
      "<p>Sehr geehrte Frau Klein,</p><p>vielen Dank für die Information zur Lieferverzögerung.</p><p>Wir bitten um eine aktualisierte Lieferbestätigung bis zum [BITTE ERGÄNZEN: Termin].</p><p>Mit freundlichen Grüßen</p><p>[SIGNATUR EINFÜGEN]</p>",
    draft_plain:
      "Sehr geehrte Frau Klein,\n\nvielen Dank für die Information zur Lieferverzögerung.\n\nWir bitten um eine aktualisierte Lieferbestätigung bis zum [BITTE ERGÄNZEN: Termin].\n\nMit freundlichen Grüßen\n[SIGNATUR EINFÜGEN]",
    placeholders: ["BITTE ERGÄNZEN: Termin"],
    reply_language: "de",
    confidence: 0.88,
    review_reason: "Fehlender konkreter Termin",
    requires_human_review: true,
    low_confidence: false,
    is_escalated: false,
    sentiment_score: -0.3,
    date: "2026-03-01T10:45:00Z",
    timestamp: "2026-03-01T10:45:00Z",
  },
  {
    workflow: "email_inbox",
    category: "URGENT",
    email_id: "urgent-003",
    sender_name: "James Richardson",
    sender_email: "j.richardson@globaltrade-ltd.co.uk",
    subject: "Re: Overdue payment — final notice",
    original_subject: "Overdue payment — final notice",
    original_preview:
      "Dear team, this is a final reminder that invoice #INV-2026-0892 for £12,500 is now 30 days overdue...",
    draft_html:
      "<p>Dear Mr Richardson,</p><p>Thank you for your message regarding invoice #INV-2026-0892.</p><p>We have forwarded the matter to our finance department and expect payment to be processed by [BITTE ERGÄNZEN: Zahlungsdatum].</p><p>Kind regards</p><p>[SIGNATUR EINFÜGEN]</p>",
    draft_plain:
      "Dear Mr Richardson,\n\nThank you for your message regarding invoice #INV-2026-0892.\n\nWe have forwarded the matter to our finance department and expect payment to be processed by [BITTE ERGÄNZEN: Zahlungsdatum].\n\nKind regards\n[SIGNATUR EINFÜGEN]",
    placeholders: ["BITTE ERGÄNZEN: Zahlungsdatum"],
    reply_language: "en",
    confidence: 0.79,
    review_reason: "International client, payment deadline missing",
    requires_human_review: true,
    low_confidence: false,
    is_escalated: false,
    sentiment_score: -0.5,
    date: "2026-03-01T08:15:00Z",
    timestamp: "2026-03-01T08:15:00Z",
  },
];

export const mockOtherDrafts: readonly DraftEmail[] = [
  {
    workflow: "email_inbox",
    category: "OTHER",
    email_id: "other-001",
    sender_name: "Emily Carter",
    sender_email: "emily.carter@partner-inc.com",
    subject: "Re: Meeting confirmation Wednesday",
    original_subject: "Meeting confirmation Wednesday",
    original_preview:
      "Hi there, can we confirm the meeting on Wednesday at 2:00 PM? Looking forward to discussing...",
    draft_html:
      "<p>Dear Emily,</p><p>Thank you for reaching out. We hereby confirm the meeting on Wednesday at 2:00 PM.</p><p>We look forward to the discussion.</p><p>Kind regards</p><p>[SIGNATUR EINFÜGEN]</p>",
    draft_plain:
      "Dear Emily,\n\nThank you for reaching out. We hereby confirm the meeting on Wednesday at 2:00 PM.\n\nWe look forward to the discussion.\n\nKind regards\n[SIGNATUR EINFÜGEN]",
    placeholders: [],
    reply_language: "en",
    confidence: 0.95,
    review_reason: "Standard confirmation, review for correctness",
    requires_human_review: true,
    low_confidence: false,
    is_escalated: false,
    sentiment_score: 0.3,
    date: "2026-03-01T09:00:00Z",
    timestamp: "2026-03-01T09:00:00Z",
  },
  {
    workflow: "email_inbox",
    category: "OTHER",
    email_id: "other-002",
    sender_name: "Markus Lehmann",
    sender_email: "lehmann@stadtwerke-koeln.de",
    subject: "Re: Allgemeine Anfrage zu Ihren Dienstleistungen",
    original_subject: "Allgemeine Anfrage zu Ihren Dienstleistungen",
    original_preview:
      "Guten Tag, wir sind an einer möglichen Zusammenarbeit interessiert. Könnten Sie uns bitte weitere...",
    draft_html:
      "<p>Sehr geehrter Herr Lehmann,</p><p>vielen Dank für Ihr Interesse an unseren Dienstleistungen.</p><p>Gerne senden wir Ihnen unser aktuelles Leistungsportfolio zu. Für ein persönliches Beratungsgespräch stehen wir Ihnen am [BITTE ERGÄNZEN: Terminvorschlag] zur Verfügung.</p><p>Mit freundlichen Grüßen</p><p>[SIGNATUR EINFÜGEN]</p>",
    draft_plain:
      "Sehr geehrter Herr Lehmann,\n\nvielen Dank für Ihr Interesse an unseren Dienstleistungen.\n\nGerne senden wir Ihnen unser aktuelles Leistungsportfolio zu. Für ein persönliches Beratungsgespräch stehen wir Ihnen am [BITTE ERGÄNZEN: Terminvorschlag] zur Verfügung.\n\nMit freundlichen Grüßen\n[SIGNATUR EINFÜGEN]",
    placeholders: ["BITTE ERGÄNZEN: Terminvorschlag"],
    reply_language: "de",
    confidence: 0.55,
    review_reason:
      "Niedrige Konfidenz bei Kategorisierung, Terminvorschlag fehlt",
    requires_human_review: true,
    low_confidence: true,
    is_escalated: false,
    sentiment_score: 0.1,
    date: "2026-02-28T15:30:00Z",
    timestamp: "2026-02-28T15:30:00Z",
  },
];

export const mockEscalations: readonly EscalationAlert[] = [
  {
    workflow: "email_inbox",
    category: "ESCALATION",
    email_id: "esc-001",
    sender_name: "Dr. Markus Braun",
    sender_email: "braun@rechtsanwalt-braun.de",
    subject: "Letzte Mahnung — Fristsetzung",
    sentiment_score: -0.8,
    urgency: 5,
    complaint_risk: true,
    legal_threat: true,
    churn_risk: "high",
    summary:
      "Anwaltliche Mahnung mit Fristsetzung. Rechtliche Schritte angedroht. Sofortige Reaktion erforderlich.",
    timestamp: "2026-03-01T13:00:00Z",
  },
  {
    workflow: "email_inbox",
    category: "ESCALATION",
    email_id: "esc-002",
    sender_name: "Petra Hoffmann",
    sender_email: "p.hoffmann@enterprise-corp.de",
    subject: "Beschwerde: Wiederholte Serviceprobleme",
    sentiment_score: -0.5,
    urgency: 4,
    complaint_risk: true,
    legal_threat: false,
    churn_risk: "high",
    summary:
      "Langjährige Kundin beschwert sich über wiederholte Ausfälle. Droht mit Anbieterwechsel. Sofortige Deeskalation empfohlen.",
    timestamp: "2026-03-01T11:30:00Z",
  },
  {
    workflow: "email_inbox",
    category: "ESCALATION",
    email_id: "esc-003",
    sender_name: "Michael Schneider",
    sender_email: "schneider@mittelstand-gmbh.de",
    subject: "Unzufriedenheit mit Lieferzeit",
    sentiment_score: -0.3,
    urgency: 3,
    complaint_risk: false,
    legal_threat: false,
    churn_risk: "medium",
    summary:
      "Kunde meldet Unzufriedenheit mit Lieferzeiten. Noch keine konkrete Drohung, aber Stimmung deutlich negativ.",
    timestamp: "2026-03-01T09:15:00Z",
  },
];

export const mockUnsubscribes: readonly UnsubscribeStatus[] = [
  {
    email_id: "unsub-001",
    sender: "newsletter@marketing-tool.com",
    unsubscribe_method: "one-click",
    status: "erfolgreich",
    reason: "One-Click-Abmeldung erfolgreich durchgeführt",
    timestamp: "2026-03-01T08:30:00Z",
  },
  {
    email_id: "unsub-002",
    sender: "info@webinar-platform.io",
    unsubscribe_method: "mailto",
    status: "nicht erfolgreich",
    reason: "Abmelde-E-Mail konnte nicht zugestellt werden (Bounced)",
    timestamp: "2026-02-28T16:45:00Z",
  },
  {
    email_id: "unsub-003",
    sender: "promo@shop-deals24.de",
    unsubscribe_method: "not-found",
    status: "nicht erfolgreich",
    reason: "Kein Abmeldelink oder Mailto-Header in der E-Mail gefunden",
    timestamp: "2026-03-01T10:00:00Z",
  },
];
